[package]
name = "ncx"
version = "0.1.1"
edition = "2024"
description = "A thin, web NetCDF viewer"
license = "MIT"

[dependencies]
axum = "0.8.9"
getrandom = "0.3.1"
hyper = { version = "1.11.0", features = ["client", "http1"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
libc = "0.2.177"
netcdf = { version = "0.12.1", default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["io-std", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
